apiVersion: apps/v1 # which api to use for deployment
kind: Deployment 

metadata: 
  name: nginx-deployment 
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  # template to use its label for k8 service to launch
  template:
    metadata:
      labels: 
        app: nginx

    spec:
      containers:
      - name: nginx
        image: r21bxl/nginx_image
        ports:
         - containerPort: 80